### ISSUE TITLE
Source license

### ISSUE THREAD

**Issue by akiross** [pravdomil/Code128#1]
Hello,
First of all, thank you for sharing: it's nice to see an elm implementation for rendering code 128 barcodes!

So, I found your repository interesting and I was thinking to use it in a small personal non-commercial project, but I couldn't find licensing info about the source, so I'd like to ask if you could possibly add some LICENSE file or some header.

Also, it would be great to have it published in https://package.elm-lang.org/ :)

Thank you!

**Comment by pravdomil** [comment]
you can use it is fine :)
