### ISSUE TITLE
Publishing to Elm packages

### ISSUE THREAD

**Issue by bramerto** [pravdomil/Code128#2]
Hello there,

I saw an earlier issue #1 about this package being free to use. Thank you so much! I was wondering if this package can be published to [elm packages](https://package.elm-lang.org/). That would integrate better, and it's the only implementation of barcodes in Elm as far as I can see. 

More info can be found here:
https://package.elm-lang.org/help/design-guidelines

Kind regards

**Comment by pravdomil** [comment]
or i can transfer ownership

**Comment by bramerto** [comment]
I don't feel that transfer of ownership is going to help, nor is me publishing it. I didn't write the code. 

Furthermore, I asked my supervisor if possibly we could transfer ownership to our company. As generating Code128 barcodes is a crucial part of our business. But alas, we are opting for a different strategy around generating barcodes. 

Thanks for the quick reply, though!

Kind regards
